# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest      #these actions runs in ubuntu virtual machine

    steps:
    - name: Checkout repository  #clone the repo inside the machine
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}    #pushing the new docker image with new tag to dockerhub..{{github.run_id}} means whenever new docker image is pushed to docker hub cretae a new tag for that new docker image

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push       #to update helm chart we need push stage

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}   #to commit to github u need github token..need to have access to github

    - name: Update tag in Helm chart   #first its searches for name tag in values.yaml using sed command and it will update the tag field in values.yaml(helm\go-webapp-chart\values.yaml) with new docker image tag created by (github.run_id)
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml        

    - name: Commit and push changes          #once the tag is updated in values.yaml..we need to push the changes in to github
      run: |
        git config --global user.email "kevin.mendis2@gmail.com"
        git config --global user.name "Yusry Yesneen"      
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push